SERVICE_UPDATE_STATE = "update_state"
CONF_MANUAL = "manual"
CONF_MAX_VOLUME = "max_volume"
CONF_PING_INTERVAL = "ping_interval"

DOMAIN = "sonyavr"
DEFAULT_NAME = "SONY AVR"
SERVICE_SEND_COMMAND = "send_command"

MAX_VOLUME = 45
MIN_VOLUME = 0
LOW_VOLUME = 15
VOLUME_STEP = 1

STR_DA5800ES_MAX_VOLUME = 20.0
STR_DA5800ES_MIN_VOLUME = -80.0
STR_DA5800ES_LOW_VOLUME = -50.0
STR_DA5800ES_VOLUME_STEP = 0.5
