send_command:
  name: Send Command
  description: Send commands to Sony AVR processor
  target:
    entity:
      integration: sonyavr
      domain: media_player
  fields:
    Command:
      name: Command
      description: "The Command to send to the AVR."
      required: true 
      selector:
        select:
          multiple: false
          options:
            - Mute
            - UnMute
            - Power On
            - Power Off
            - Volume Up
            - Volume Down
            - Source Up
            - Source Down
            - Set Volume
            - Set Sound Field
            - Set Source
    Value:
      name: Command Value
      description: "The value associated with the command."
      required: false
      selector:
        text:

discover:
  name: Discover Sony AVR 
  description: Discover Sony AVR on the network and update states


